obj-$(CONFIG_USE_DIRECT_IS_CONTROL) += fimc-is-interface-ischain.o \
		fimc-is-interface-library.o \
		fimc-is-interface-vra.o \
		fimc-is-interface-ddk.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-r7/
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-r7/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-r7/hardware
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-r7/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-r7/vendor
