obj-$(CONFIG_CAMERA_APERTURE_AK7372_OBJ) += fimc-is-aperture-ak7372.o

ccflags-y := -Idrivers/media/platform/exynos/fimc-is2-r7
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2-r7/include
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2-r7/vendor
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2-r7/hardware/api
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2-r7/sensor
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2-r7/sensor/module_framework
