obj-$(CONFIG_CAMERA_FPGA_DPHY) += fimc-is-fpga-dphy.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-r7
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-r7/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-r7/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-r7/sensor
